#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Dec  4 16:09:44 2019

@author: maximecarriere
"""



import matplotlib.pyplot as plt
import mplleaflet
import pandas as pd
import numpy as np
import datetime as dt
import matplotlib.dates as mdates

df = pd.read_csv('/Users/maximecarriere/Downloads/fb441e62df2d58994928907a91895ec62c2c42e6cd075c2700843b89.csv')

df =df.sort_values('Date')

print(df.head())

df['Date']= pd.to_datetime(df['Date'])
df['year'] = df['Date'].dt.year # Extracting year from date



df = df[(df['Date'].dt.month !=2) + (df['Date'].dt.day != 29)]
df = df.set_index('Date')



df_2015 = df[df['year']==2015] # keep 2015
df_2005_2014 = df[df['year']!=2015] # keep 2005-2014



dfmax_2005_2014 = df_2005_2014.groupby(lambda x : '{:02d}-{:02d}'.format(x.month, x.day))['Data_Value'].max()/10
dfmin_2005_2014 = df_2005_2014.groupby(lambda x : '{:02d}-{:02d}'.format(x.month, x.day))['Data_Value'].min()/10



dfmax_2015 = df_2015.groupby(lambda x : '{:02d}-{:02d}'.format(x.month, x.day))['Data_Value'].max()/10
dfmin_2015 = df_2015.groupby(lambda x : '{:02d}-{:02d}'.format(x.month, x.day))['Data_Value'].min()/10

#df_date =df.sort_values('Date')




fig, ax = plt.subplots()
# add a label to the x axis
plt.xlabel('Time')
# add a label to the y axis
plt.ylabel('Temperature ($C°$)')
# add a title
plt.title('Comparison of Maximum and Minimum of Temperature')


x = [i for i in range(len(dfmax_2005_2014))]
ax = plt.plot(x, dfmax_2005_2014,markerfacecolor='blue',label='Max 2005-2014')
ax = plt.plot(x, dfmin_2005_2014,markerfacecolor='crimson',label='Min 2005-2014')
ax = plt.scatter(x, dfmax_2015,s=5,c='navy',label='Max 2015')
ax = plt.scatter(x, dfmin_2015,s=5,c='firebrick',label='Min 2015')
ax = plt.gca().fill_between(range(len(x)), 
                       dfmax_2005_2014, dfmin_2005_2014, 
                       facecolor='grey', 
         
              alpha=0.20)


plt.legend()

plt.savefig('bouboubou.png', dpi = 1200)


